name: Preetam Pothala

repo_names:
  - App

# Provide any URLs for your Videos
10-ux-ui-criticism:
  - https://youtu.be/6KNTznFX240
  - https://youtu.be/0lPQZqeX_40

project-check-in-1: https://github.com/preetampothala/ATLAS-iOS-Fall-22/issues/3
