name: Preetam Pothala

repo_names:
  - App

# Provide any URLs for your Videos
10-ux-ui-criticism:
  - https://youtu.be/6KNTznFX240
  - https://youtu.be/0lPQZqeX_40

# Provide any URLs for your Data Models assignment
11-models-from-data:
